name: basic
on:
  - pull_request
  - push
  - workflow_dispatch
jobs:
  check:
    name: Check L1.agda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: wenkokke/setup-agda@v2
        with:
          agda-version: '2.6.4.1'
          agda-stdlib-version: 'recommended'

      - run: agda -c -i $HOME/.agda/libraries.d/standard-library/v2.0/src L1-Theorems.agda
      - run: agda -c -i $HOME/.agda/libraries.d/standard-library/v2.0/src L2-Examples.agda
